version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: eventpulse-postgres
    restart: always
    environment:
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventpulse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
